name: lge2020
description: Local Government Elections KP 2020

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.0.1
  cupertino_icons: ^0.1.2
  location: ^1.4.1
  firebase_core: ^0.4.0+9
  firebase_storage: ^1.0.4
  firebase_auth: ^0.14.0+5
  image_picker:
  date_format: ^1.0.5
  modal_progress_hud: ^0.1.2
  simple_permissions: "^0.1.2"
  shared_preferences: "^0.4.3"
  #cloud_firestore: ^0.8.0
  cloud_firestore: ^0.12.9+5
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/wards.png
    - assets/images/districts.png
    - assets/images/ro.png
    - assets/images/blocks.png
    - assets/images/councils.png
    - assets/images/01.png
  fonts:
    - family: dancingscript
      fonts:
        - asset: assets/fonts/dancingscript.ttf
    - family: mashan
      fonts:
        - asset: assets/fonts/mashan.ttf
    - family: rightous
      fonts:
        - asset: assets/fonts/rightous.ttf
    - family: shadowintolight
      fonts:
        - asset: assets/fonts/shadowintolight.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
